### ISSUE TITLE
Unable to build because of static include paths

### ISSUE THREAD

**Issue by MrHillo** [Volantus/berry-spi#4]
I was unable to build cause of the static include paths, so i did some changes to the Makefile.

Add:
`INCLUDE_DIR			=	$(shell php-config --include-dir)`
and replaced:
`COMPILER_FLAGS		=	-Wall -I/usr/local/src/php -I/usr/local/src/php/main -I/usr/local/src/php/Zend -I/usr/local/src/php/TSRM -c -O2 -std=c++11 -fpic -o`
with:
`COMPILER_FLAGS		=	-Wall -I$(INCLUDE_DIR) -I$(INCLUDE_DIR)/main -I$(INCLUDE_DIR)/Zend -I$(INCLUDE_DIR)/TSRM -c -O2 -std=c++11 -fpic -o`

I can make a pull request if wanted.

**Comment by marius-meissner** [comment]
Thanks a lot!
I would really appreciate it if you could open a Pull Request.

**Comment by MrHillo** [comment]
done #6
